default:
  base_config:
    env_type: GYM
    scene: MyOpensimEnv

    build_path: MyOpensimEnv-v1
    
    max_step: -1
    max_iter: 1000000
    n_agents: 30
    reset_on_iteration: true
  replay_config:
    batch_size: 256
    capacity: 100000
    # use_priority: false
    alpha: 0.
    beta_increment_per_sampling: 0

  sac_config:
    save_model_per_step: 300 # Save model every N steps
    save_model_per_minute: 3 # Save model every N minutes

    learning_rate: 0.001

    n_step: 3
    clip_epsilon: -1

    discrete_dqn_like: true

    use_n_step_is: true
    use_priority: false
    use_normalization: true
    use_rnd: false
